PROGRAM1=grads_ctl.sh
PROGRAM2=grads_ctl.pl
PROGRAM3=exist_data.sh
PROGRAM4=grads_ctl2.pl

VERSION=dev
#VERSION=0.10b3

INSTALL=/home/kodama/bin


install:
	cp ${PROGRAM1} ${PROGRAM1}-${VERSION}
	mv ${PROGRAM1}-${VERSION} ${INSTALL}
	rm -f ${INSTALL}/${PROGRAM1}
	ln -s ${INSTALL}/${PROGRAM1}-${VERSION} ${INSTALL}/${PROGRAM1}
	cp ${PROGRAM2} ${PROGRAM2}-${VERSION}
	mv ${PROGRAM2}-${VERSION} ${INSTALL}
	rm -f ${INSTALL}/${PROGRAM2}
	ln -s ${INSTALL}/${PROGRAM2}-${VERSION} ${INSTALL}/${PROGRAM2}
	cp ${PROGRAM3} ${PROGRAM3}-${VERSION}
	mv ${PROGRAM3}-${VERSION} ${INSTALL}
	rm -f ${INSTALL}/${PROGRAM3}
	ln -s ${INSTALL}/${PROGRAM3}-${VERSION} ${INSTALL}/${PROGRAM3}
	cp ${PROGRAM4} ${PROGRAM4}-${VERSION}
	mv ${PROGRAM4}-${VERSION} ${INSTALL}
	rm -f ${INSTALL}/${PROGRAM4}
	ln -s ${INSTALL}/${PROGRAM4}-${VERSION} ${INSTALL}/${PROGRAM4}
